language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - tools
     - platform-tools
     - tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28

    - add-on
    - extra

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-17

  licenses:
      - 'android-sdk-license-.+'

  notifications:
      email: false

script:
  - ./gradlew build connectedCheck --info


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache