language: android        #语言说明
jdk: oraclejdk8          #jdk版本
sudo: required           #权限要求
env:                 #环境变量
global:
- ANDROID_API=28
- EMULATOR_API=28
- ANDROID_BUILD_TOOLS=28.0.2
- ADB_INSTALL_TIMEOUT=5 # minutes
android:             #Android 环境要求
 components:
- tools
- platform-tools
- build-tools-$ANDROID_BUILD_TOOLS
- android-$ANDROID_API
- android-$EMULATOR_API
- extra-google-m2repository
- extra-android-m2repository        # 配置design 库
- addon-google_apis-google-19       # 配置google play services
- sys-img-armeabi-v7a-android-$ANDROID_API
- sys-img-armeabi-v7a-android-$EMULATOR_API
licenses:               #内容许可添加
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+