language: android
jdk: oraclejdk8
sudo: required
env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=28.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: lF8xVb1DHPkPuhsmRC5IUAx5hDqBLjxKCUaljo7A+PeWq+l61b/XrCFYvSAAoyhn1NKzV0GOZ2Qo4tYyLQZZa6q1CLiQNtF10NpRWkfROjgwY7oXzB1YdfIEZzBJJgS4ISHR4AzEdZhGJki6mPJ3bhMvF5Jy+1QsNEsPQxhEcxiKa9gKmZkMEQ88DfUYZWL61gsum0S03Xm3KgJz5EH8CxvypHiC8RK8Ev3v8LEQiQ/T7Yyz7+5rxeE7nQOLrfbYEJw1ApfmL0G68ZfTAJJ76R/RoSNp9eCNFCr685//ApV9qQ/pkG4EQ8ozSGUpBNujN1wtkzveSxmDbe51ftk9K8FRu7owAqvLIo0RAkfmL7GSLtUi+eoc8TGdGmn0chkKJ8xkyyMF94U2teVP5aZssUF0odFzlfaPCFA5hDnU1Opek74q7eoh2+QHcEX06UQq41NAclsT5iHmMKwP5e+FECAGKYQQbOI8hPylWVdkjq0fnJKjVCPMrb3fnuL89APl/qIa1yeSC8l0L6oEkQp5Ta54NK3xTQ+C89UJll+lL5FCGNTr6xnkwYkAhMyOPdQmOM0qrxXsdK5CMFTHktH+kHhj/EeZJfd+IOBFpbnDrlWWHiVpjardT9V5phgZusR9Thshyy6pKwItjG7PaubEgb1yRcW4jrd5LsoS3iHwZlA=
  - secure: I/iQiSR1Fkx4ZpDIEjJIdvxr5o61C9n61QquVYkoZDbSGC1aBbGmnDqUmeUt2Ljbge/1CxRBoEq0ktjjs+Nm+8Pyt8LMlPMi8Gn3hjcfceAVCvWd/dWT8xETdK2LKC1s05H64wCoIwW/3MSHsfIIhea2YkubiM5Feyw6DN/wUZGojT1WnxlkwSMVjAzRS8ejT9U/c54NYYeuDMQ9ytrn++Z4hoD+dhViKK10UQJ/3r3O2kog9VOjjkThqtrktbHk0tw0uVOv0BXWmfbIcwZNt7x8t0AMnohgyW69NY/8uWR4KspgWj71J2kIzR4BBQ5EmL3rJCaoZ/6nC+KmY4HXxNSd3Wn2F1/ll/OPDhHnY7RcJmkVj6UI2lAkjkjVClYFCRwbuuTsvlHdVFLjYz068DtpkeIAJgv3ajmCG+gFcHMxCKPodSmsqYkoDakEawo8OFzi0zz9c7u0FzE4Ynr3lAXmqgNWfm33+8xT7vMKa6WlSj0EY23fY06CAg8lHptvsIuWAUKPCEIBp5YRjMNDAqn7DljcN/D+pyZ3FpNeCG0sSxflUeJIa3s2Gm0dOzW82UomSSxA1cT/hM5X8hSFRoTtTL6/Pwp4/MfOO0Z1oZy0pp8LQbj8Z0swf2D2lWaDwJSyd0CAuwPH6KPiFSZxXOc5dCy2vothmfcKcg8O0MU=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$ANDROID_API
  - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
#for test
#- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#- emulator -avd test -no-audio -no-window &
#- android-wait-for-emulator
before_install:
- openssl aes-256-cbc -K $encrypted_f95ceee5962c_key -iv $encrypted_f95ceee5962c_iv
  -in appkey.jks.enc -out appkey.jks -d
- chmod +x gradlew
- cd $TRAVIS_BUILD_DIR
- wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh
  -O pgyer_upload.sh
- chmod +x pgyer_upload.sh
script:
- ./gradlew assembleRelease
after_success:
- cp $TRAVIS_BUILD_DIR/appkey.jks $HOME
- cd $TRAVIS_BUILD_DIR/app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/appkey.jks
  - storepass $storepass -keypass $keypass app-release-unsigned.apk lime
- jarsigner -verify app-release.apk
- "${ANDROID_HOME}/build-tools/28.0.2/zipalign -v 4 app-release.apk lime.apk"
after_script:
- set -e
- $TRAVIS_BUILD_DIR/pgyer_upload.sh "${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/lime.apk"
  "318e91cdb7e069286d1dcc56acfe203a"
- rm $TRAVIS_BUILD_DIR/pgyer_upload.sh
