codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "app/src/main/java/com/moi/lime/vo/.*"
  - "app/src/main/java/com/moi/lime/di/.*"
  - "app/src/main/java/com/moi/lime/LimeApp.kt"  
  - "app/src/main/java/com/moi/lime/viewmodel/LimeViewModelFactory.kt"
  - "buildSrc"
